# Generated by Django 5.0.7 on 2025-09-14 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('LIKE', 'Новая симпатия'), ('MESSAGE', 'Новое сообщение')], max_length=10, verbose_name='Тип уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=10, verbose_name='Пол')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pics/%Y/%m/%d/', verbose_name='Фотография профиля')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('marital_status', models.CharField(choices=[('Не женат/Не замужем', 'Не женат/Не замужем'), ('Разведен(а)', 'Разведен(а)'), ('Вдовец/Вдова', 'Вдовец/Вдова')], max_length=50, verbose_name='Семейное положение')),
                ('children', models.CharField(choices=[('Нет', 'Нет'), ('Есть', 'Есть')], max_length=50, verbose_name='Дети')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Образование')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Профессия')),
                ('churching_level', models.CharField(choices=[('Новоначальный', 'Новоначальный'), ('Воцерковленный', 'Воцерковленный')], max_length=50, verbose_name='Степень воцерковленности')),
                ('attitude_to_fasting', models.CharField(choices=[('Соблюдаю', 'Соблюдаю'), ('Не соблюдаю', 'Не соблюдаю')], max_length=50, verbose_name='Отношение к постам')),
                ('sacraments', models.CharField(choices=[('Регулярно', 'Регулярно'), ('Иногда', 'Иногда'), ('Редко', 'Редко')], max_length=50, verbose_name='Участие в Таинствах')),
                ('favorite_saints', models.CharField(blank=True, max_length=255, verbose_name='Любимые святые')),
                ('spiritual_books', models.TextField(blank=True, verbose_name='Любимые духовные книги')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
