# Generated by Django 5.2.5 on 2025-08-31 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомлениях',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/', verbose_name='Фотография')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
                ('marital_status', models.CharField(choices=[('Не женат/Не замужем', 'Не женат/Не замужем'), ('Разведен(а)', 'Разведен(а)'), ('Вдовец/Вдова', 'Вдовец/Вдова')], max_length=50, verbose_name='Семейное положение')),
                ('children', models.CharField(choices=[('Нет', 'Нет'), ('Есть, живут со мной', 'Есть, живут со мной'), ('Есть, живут отдельно', 'Есть, живут отдельно')], max_length=50, verbose_name='Дети')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Образование')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Профессия/Род деятельности')),
                ('parish', models.CharField(blank=True, max_length=255, verbose_name='Приход, который посещает')),
                ('churching_level', models.CharField(choices=[('Новоначальный', 'Новоначальный'), ('Воцерковленный', 'Воцерковленный'), ('Глубоко верующий', 'Глубоко верующий')], max_length=50, verbose_name='Степень воцерковленности')),
                ('attitude_to_fasting', models.TextField(blank=True, verbose_name='Отношение к постам')),
                ('sacraments_participation', models.TextField(blank=True, verbose_name='Участие в таинствах (Исповедь, Причастие)')),
                ('favorite_saints', models.CharField(blank=True, max_length=255, verbose_name='Любимые святые')),
                ('spiritual_books', models.TextField(blank=True, verbose_name='Любимые духовные книги')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
