databases:
  - name: orthodox-dating-db
    plan: free
    databaseName: orthodox_dating_project
    user: orthodox_dating_project


services:
  - type: web
    plan: free
    name: orthodox_dating_project

    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn orthodox_dating_project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: orthodox-dating-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
